class Country:
	country_name = {'Australia': 'au',
			   'Austria': 'at',
			   'Belgium': 'be',
			   'Brazil': 'br', 
			   'Bulgaria': 'bg', 
			   'Canada': 'ca', 
			   'China': 'cn', 
			   'Colombia': 'co', 
			   'Cuba': 'cu', 
			   'Egypt': 'eg', 
			   'France': 'fr', 
			   'Germany': 'de', 
			   'Greece': 'gr', 
			   'Hungary': 'hu', 
			   'India': 'in', 
			   'Indonesia': 'id', 
			   'Ireland': 'ie', 
			   'Israel': 'il', 
			   'Italy': 'it', 
			   'Japan': 'jp', 
			   'Latvia': 'lv', 
			   'Lithuania': 'lt', 
			   'Malaysia': 'my', 
			   'Mexico': 'mx', 
			   'Morocco': 'ma', 
			   'Netherlands': 'nl', 
			   'Nigeria': 'ng', 
			   'Norway': 'no', 
			   'Philippines': 'ph', 
			   'Poland': 'pl', 
			   'Portugal': 'pt', 
			   'Romania': 'ro', 
			   'Russia': 'ru', 
			   'Serbia': 'rs', 
			   'Singapore': 'sg', 
			   'Slovakia': 'sk', 
			   'Slovenia': 'si', 
			   'Sweden': 'se', 
			   'Switzerland': 'ch', 
			   'Taiwan': 'tw', 
			   'Thailand': 'th', 
			   'Turkey': 'tr', 
			   'UAE': 'ae', 
			   'Ukraine': 'ua', 
			   'Venuzuela': 've'
			   }

	catagory = ['business' , 
				'entertainment', 
				'health' , 
				'science' , 
				'sports' , 
				'technology'
				]